; screen.asm
                        ORG $0000
Screen:
                        out (ULA_PORT), a               ; More precise to start ISR with OUT
                        nextreg 7, %00                  ; Switch to 3.5MHz to sync frame to 0T
                        nextreg 7, %10                  ; Switch back to 14MHz, now synced to 0T
                        IF INCHPATTERN == 1
                            INCLUDE hpattern.asm        ; Programmatically generated by PatternGen.exe
                        ELSE
                            REPT 5838                   ; At VGA50 14MHz +3 timing this covers 320x256 layer 2
                                nextreg 18, 9           ; 5,838 x 2 = 11,676 
                                nextreg 18, 14          ; 11,676 x 20T = 233,520T
                            ENDR
                        ENDIF
                        nextreg 18, 9                   ; This occurs after the end of 320x256 layer 2
                        BORDER 0                        ; Constant timing so we can change colours
                        REPT 7                          ; Any necessary timing padding
                            cp 0
                        ENDR
                        inc iy
                        ld a, 0                         ; Set A for border change next frame     
                        ei
                        reti

                        DISPLAY "Last Screen=", $